"""empty message

Revision ID: 0b050f1c1995
Revises: c972d71f54d3
Create Date: 2019-09-17 21:54:33.657017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b050f1c1995'
down_revision = 'c972d71f54d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('address', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
