"""empty message

Revision ID: 3c16889a6ef5
Revises: 0b050f1c1995
Create Date: 2019-09-17 22:04:35.318635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c16889a6ef5'
down_revision = '0b050f1c1995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('yahoo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'yahoo')
    # ### end Alembic commands ###
