"""empty message

Revision ID: 4235ca5cb396
Revises: ac086b19c5f0
Create Date: 2019-09-17 22:20:16.954061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4235ca5cb396'
down_revision = 'ac086b19c5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regtb') as batch_op:
         batch_op.drop_column('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('address', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
