"""empty message

Revision ID: 44c85890b7c2
Revises: c47235fff6f4
Create Date: 2019-09-17 19:09:30.647523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c85890b7c2'
down_revision = 'c47235fff6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('userpix3', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'userpix3')
    # ### end Alembic commands ###
