"""empty message

Revision ID: 5c9c73e35be2
Revises: 44c85890b7c2
Create Date: 2019-09-17 19:13:48.216610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9c73e35be2'
down_revision = '44c85890b7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'userpix3')
    op.drop_column('regtb', 'userpix2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('userpix2', sa.VARCHAR(length=200), nullable=True))
    op.add_column('regtb', sa.Column('userpix3', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
