"""empty message

Revision ID: 609ac177a57c
Revises: 39c68b7f4188
Create Date: 2019-12-07 21:50:36.003149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609ac177a57c'
down_revision = '39c68b7f4188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactmsgtb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('today', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contactmsg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactmsg',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), nullable=True),
    sa.Column('today', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contactmsgtb')
    # ### end Alembic commands ###
