"""empty message

Revision ID: 954967dc4cde
Revises: 
Create Date: 2019-09-17 18:39:13.024170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954967dc4cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('userid', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'userid')
    # ### end Alembic commands ###
