"""empty message

Revision ID: ac086b19c5f0
Revises: 3c16889a6ef5
Create Date: 2019-09-17 22:05:36.728121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac086b19c5f0'
down_revision = '3c16889a6ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'yahoo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('yahoo', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
