"""empty message

Revision ID: c972d71f54d3
Revises: b96c59ee34a0
Create Date: 2019-09-17 21:49:43.057690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c972d71f54d3'
down_revision = 'b96c59ee34a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regtb', sa.Column('address', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regtb', 'address')
    # ### end Alembic commands ###
